name: Build and Deploy .NET Application

on:
  push:
    branches:
      - backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build and Test
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        env:
          DOTNET_ROOT: /home/runner/.dotnet
        run: dotnet test

      - name: Publish
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
        env:
          DOTNET_ROOT: /home/runner/.dotnet
        run: dotnet publish --configuration Release --output ./publish
        if: success()

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-files
          path: ./publish
        if: success()

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: published-files
          path: ./published-files
        if: success()
