name: Build and Deploy .NET Application

on:
  push:
    branches: [ backend ]    # run only when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest    # use the latest version of Ubuntu
    steps:
    - uses: actions/checkout@v2    # checkout the code from the repository
    - name: Setup .NET    # install .NET on the machine
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'    # specify the version of .NET to be installed
    - name: Restore Dependencies    # restore the NuGet packages
      run: dotnet restore
    - name: Build Application    # build the .NET application
      run: dotnet build --configuration Release --no-restore
    - name: Publish Artifact   # publish the artifact
      run: dotnet publish --configuration Release --output ./publish
    - name: Download Artifact   # download the artifact
      uses: actions/download-artifact@v2
      with:
        name: published-files
        path: ./published-files
